name: Reviewdog eslint
on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses:
      - uses: actions/checkout@3
      - uses: actions/setup-node@v3
      - run: cd src && npm install
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          eslint_flags: './src/'